baseURL = ""
languageCode = "en-us"
title = "Aditi Laddha"
theme = "notrack"
newContentEditor = "nvim"
mainSections = ["Publications"]
# disqusShortname = "example"
paginate = 4

[params]
  author = "Aditi Laddha"
  siteHeading = "Aditi Laddha" # defaults to author
  favicon = "" # Adds a small icon next to the page title in a tab
  mainSections = ["Publications"]
  showTaxonomyLinks = false
  nBlogLatest = 100 # number of blog post om the home page
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
  [params.social]
    github = "aditiladdha"
    linkedin = "aditi-laddha-938218144/"
    email = "aladdha6@gatech.edu"
    googlescholar = "citations?hl=en&user=zJ3W7ccAAAAJ"

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"
